<?php
/**
 * @copyright Copyright (c) 2023 Magebit (https://magebit.com/)
 * @author    <info@magebit.com>
 * @license   GNU General Public License ("GPL") v3.0
 *
 * For the full copyright and license information, please view the LICENSE
 * file that was distributed with this source code.
 *
 *  if widget.xml parameter 'display_mode' option value = 1 then show all CMS pages;
 *  if widget.xml parameter 'display_mode' option value = 0 then show only selected CMS pages
 */

/** @var Escaper $escaper */
/** @var PageList $block */
use Magebit\PageListWidget\Block\Widget\PageList;
use Magento\Framework\Escaper;
?>

<h3><?= $escaper->escapeHtml($block->getData('title')) ?></h3>
<ul>
    <?php if ($block->getDisplayMode() === 1): ?>
        <?php $cmsPages = $block->getCmsPages(); ?>
        <?php foreach ($cmsPages as $page): ?>
            <li>
                <a href="<?= /* @noEscape */ $block->getUrl('cms/page/view', ['page_id' => $page->getId()]); ?>">
                    <?= $escaper->escapeHtml($page->getTitle()); ?>
                </a>
            </li>
        <?php endforeach; ?>
    <?php elseif ($block->getDisplayMode() === 0): ?>
        <?php foreach ($block->getSelectedPageIds() as $pageId): ?>
            <?php $page = $block->getCmsPageById($pageId); ?>
            <?php if ($page): ?>
                <li>
                    <a href="<?= /* @noEscape */  $block->getUrl('cms/page/view', ['page_id' => $page->getId()]); ?>">
                        <?= $escaper->escapeHtml($page->getTitle()); ?>
                    </a>
                </li>
            <?php endif; ?>
        <?php endforeach; ?>
    <?php endif; ?>
</ul>
